name: Office
favicon: null
layout_spectrum: 0.3665249007754028
typography_spectrum: 0.11455000238493085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b43433'
    - '#3c3b41'
    - '#b0b0b2'
    - '#ce7576'
  brandStrength: 0.3125
  lightness: 0.8588559806812555
  saturation: 0.030807788716629148
  rhythmicContrast: 0.2089783742558211
purpose: []
